version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    container_name: backend
    volumes:
      - ./apps/backend:/app
    ports:
      - '8000:8000'
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    container_name: frontend
    volumes:
      - ./apps/frontend:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    depends_on:
      - backend
    environment:
      - NODE_ENV=development
    command: pnpm dev --host 0.0.0.0 --port 3000
